stages:
  - build
  - deploy
  - latest

variables:
  REGISTRY: $CI_REGISTRY_IMAGE/pbs

defaults:
  image: docker:20.10

  services:
    - docker:20.10-dind

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.make_tag_version:
  script:
    - make $CI_JOB_NAME VERSION=$CI_COMMIT_TAG
  only: [tags]

amd64-push:
  extends: .make_tag_version
  stage: build
  tags: amd64

arm64v8-push:
  extends: .make_tag_version
  stage: build
  tags: arm64

all-manifest:
  extends: .make_tag_version
  stage: deploy
  tags: amd64

all-latest:
  extends: .make_tag_version
  stage: latest
  tags: amd64
  when: manual

